#!/bin/bash

ID=`cat /etc/machine-id`

# ------------------------------

AES_STORAGE="$OBSIDIAN_KEY_STORAGE_ORIGIN/aes"
RSA_STORAGE="$OBSIDIAN_KEY_STORAGE_ORIGIN/rsa"
RSA_PUB_STORAGE="$RSA_STORAGE/pub"
RSA_PRV_STORAGE="$RSA_STORAGE/prv"

RSA_PRIVATE_KEY_FILE="$RSA_PRV_STORAGE/$ID.pem"
RSA_PUBLIC_KEY_FILE="$RSA_PUB_STORAGE/$ID.pem"
AES_KEY_FILE="$AES_STORAGE/$ID.bin"

# ------------------------------

OBSIDIAN_RSA_KEYS_STORAGE="$OBSIDIAN_KEY_STORAGE_PUBLIC/rsa"
OBSIDIAN_AES_ENC_STORAGE="$OBSIDIAN_KEY_STORAGE_PUBLIC/aes"

RSA_PUB_FILE="$OBSIDIAN_RSA_KEYS_STORAGE/$ID.pem"
AES_ENC_FILE="$OBSIDIAN_AES_ENC_STORAGE/$ID.bin.encrypted"
